### PR TITLE
WIP add #to_ast to relevant objects

### PR DESCRIPTION
**Pull request by solnic**
As discussed I'm working on adding `#to_ast` to axiom's relations so we could integrate it easily with the new sql generator.

This PR shows current status. Please chime in if you have ideas how the ast should look like. As a good start I'm using mbj's axiom-sexp as an inspiration:
- [x] Relation::Base                            => [ :base                                       ]
- [x] Relation::Materialized                    => [ :materialized                               ]
- [x] Relation::Operation::Sorted                => [ :binary,    :sorted, :operand, :directions   ]
- [x] Relation::Header                          => [ :collect                                    ]
- [x] Relation::Operation::Sorted::DirectionSet  => [ :collect                                    ]
- [x] Relation::Operation::Sorted::Ascending     => [ :unary,     :asc,  :attribute               ]
- [x] Relation::Operation::Sorted::Descending    => [ :unary,     :desc, :attribute               ]
- [x] Relation::Operation::Limit                => [ :binary,    :limit, :operand, :limit        ]
- [x] Relation::Operation::Offset               => [ :binary,    :offset, :operand, :offset      ]
- [x] Relation::Operation::Deletion             => [ :binary,    :delete, :operand, :other       ]
- [x] Relation::Operation::Insertion            => [ :binary,    :insert, :operand, :other       ]
- [x] Relation::Operation::Reverse              => [ :unary,     :reverse                        ]
- [x] Algebra::Difference                       => [ :binary,    :difference                     ]
- [ ] Algebra::Extension                        => [ :extend                                     ]
- [ ] Algebra::Intersection                     => [ :intersect                                  ]
- [ ] Algebra::Join                             => [ :binary,    :join                           ]
- [ ] Algebra::Product                          => [ :binary,    :product                        ]
- [ ] Algebra::Projection                       => [ :binary,    :project, :operand, :header     ]
- [ ] Algebra::Rename                           => [ :binary,    :rename                         ]
- [x] Algebra::Restriction                      => [ :binary,    :restrict, :operand, :predicate ]
- [ ] Algebra::Summarization                    => [ :binary,    :summarize                      ]
- [x] Algebra::Union                            => [ :binary,    :union                          ]
- [ ] Function::Connective::Conjunction         => [ :binary,    :and                            ]
- [ ] Function::Connective::Disjunction         => [ :binary,    :or                             ]
- [ ] Function::Connective::Negation            => [ :unary,     :not                            ]
- [ ] Function::String::Length                  => [ :unary,     :length                         ]
- [x] Function::Predicate::Equality             => [ :binary,    :eq                             ]
- [x] Function::Predicate::Exclusion            => [ :binary,    :ex                             ]
- [x] Function::Predicate::GreaterThan          => [ :binary,    :gt                             ]
- [x] Function::Predicate::GreaterThanOrEqualTo => [ :binary,    :gte                            ]
- [x] Function::Predicate::Inclusion            => [ :binary,    :in                             ]
- [x] Function::Predicate::Inequality           => [ :binary,    :neq                            ]
- [x] Function::Predicate::LessThan             => [ :binary,    :lt                             ]
- [x] Function::Predicate::LessThanOrEqualTo    => [ :binary,    :lte                            ]
- [x] Function::Predicate::Match                => [ :binary,    :match                          ]
- [x] Function::Predicate::NoMatch              => [ :binary,    :no_match                       ]
- [ ] Function::Numeric::Absolute               => [ :binary,    :abs                            ]
- [ ] Function::Numeric::Addition               => [ :binary,    :add                            ]
- [ ] Function::Numeric::Division               => [ :binary,    :div                            ]
- [ ] Function::Numeric::Exponentiation         => [ :binary,    :exp                            ]
- [ ] Function::Numeric::Modulo                 => [ :binary,    :mod                            ]
- [ ] Function::Numeric::Multiplication         => [ :binary,    :mul                            ]
- [ ] Function::Numeric::SquareRoot             => [ :unary,     :sqr                            ]
- [ ] Function::Numeric::Subtraction            => [ :binary,    :sub                            ]
- [ ] Function::Numeric::UnaryMinus             => [ :unary,     :unary_minus                    ]
- [ ] Function::Numeric::UnaryPlus              => [ :unary,     :unary_plus                     ]
- [ ] Function::Proposition::Tautology          => [ :static,    :true                           ]
- [ ] Function::Proposition::Contradiction      => [ :static,    :false                          ]
- [x] Attribute::String                         => [ :attribute                                  ]
- [x] Attribute::Integer                        => [ :attribute                                  ]

NOTES:
- I moved all unit specs to spec-old as I'm not yet sure what to do with them - as I said before I'm no longer a fan of this kind of unit tests and this style of rspec specs. I'll figure it out after I'm done with ast addition
- I'm not going to make rake ci pass as it's too much work so it's very likely this will remain under rom-rb for some time
- My biggest priority is to learn axiom's internals and make it work with the new sql generator and see the whole ROM test suite passing using this fork
- My coding style diverged a little bit from what it used to be so if you see differences and you don't like it tell me and let's discuss it

### CODE REVIEW

**Comment by mbj** [comment]
@solnic JFYI I created `axiom-sexp` a while ago. I initially planned to to port it to `axiom-ast`. Dunno fo that code from that time is any help. But I wanted to let you know.

**Comment by solnic** [comment]
Thanks. I'm just using same structure for the ast as you have there. Some classes are now different though but it's not a big deal.

**Comment by mbj** [comment]
k. I'll do a pass over the stuff you plan here, when I find time for OSS. Really like to see activity on that part.

**Comment by solnic** [comment]
Awesome, I really appreciate your input. I'll quickly jump to making it work with sql gem too just to learn how to do it. I may just create a prototype first.

**Pull request closed without merging**
